name: schedule

on:
  schedule:
    - cron: "*/20 * * * *"
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: reboot
        run: |
          curl ${{secrets.TWEET_REMINDER_BASE_URL}}
